export const LatestJob = [
  {
    title: "Senior Backend Engineer",
    companyType: "Google",
    location: "Lisbon, UK",
    jobDesc: [
      "Work with the team to design and iOS mobile applications on Azure using Swift and Objective-C.",
      "Understanding, assessing, analyzing user requirements and function specification",
      "Prepare detail technical specification",
      "Function design and implementation for new features.",
      "Production maintenance and enhancement",
      "Prepare test case, conduct the unit test and system test.",
      "Communicate with IT PM and user about solution and development progress",
    ],
  },
  {
    title: "Junior Frontend Engineer",
    companyType: "Facebook",
    location: "Lisbon, USA",
    jobDesc: [
      "Work with the team to design and iOS mobile applications on Azure using Swift and Objective-C.",
      "Understanding, assessing, analyzing user requirements and function specification",
      "Prepare detail technical specification",
      "Function design and implementation for new features.",
      "Production maintenance and enhancement",
      "Prepare test case, conduct the unit test and system test.",
      "Communicate with IT PM and user about solution and development progress",
    ],
  },
  {
    title: "Backend Engineer",
    companyType: "Amazon",
    location: "Lisbon, China",
    jobDesc: [
      "Work with the team to design and iOS mobile applications on Azure using Swift and Objective-C.",
      "Understanding, assessing, analyzing user requirements and function specification",
      "Prepare detail technical specification",
      "Function design and implementation for new features.",
      "Production maintenance and enhancement",
      "Prepare test case, conduct the unit test and system test.",
      "Communicate with IT PM and user about solution and development progress",
    ],
  },
  {
    title: "Junior Full Stack Engineer",
    companyType: "Google",
    location: "Lisbon, Portugal",
    jobDesc: [
      "Work with the team to design and iOS mobile applications on Azure using Swift and Objective-C.",
      "Understanding, assessing, analyzing user requirements and function specification",
      "Prepare detail technical specification",
      "Function design and implementation for new features.",
      "Production maintenance and enhancement",
      "Prepare test case, conduct the unit test and system test.",
      "Communicate with IT PM and user about solution and development progress",
    ],
  },
  {
    title: "Senior full Stack Engineer",
    companyType: "ZOHO",
    location: "Chennai, India",
    jobDesc: [
      "Work with the team to design and iOS mobile applications on Azure using Swift and Objective-C.",
      "Understanding, assessing, analyzing user requirements and function specification",
      "Prepare detail technical specification",
      "Function design and implementation for new features.",
      "Production maintenance and enhancement",
      "Prepare test case, conduct the unit test and system test.",
      "Communicate with IT PM and user about solution and development progress",
    ],
  },
];
